### ISSUE TITLE
Memcache-Tomcat integration is not working for multiple tabs.

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#205] opened 2015-08-24 07:31 UTC
_From [shaikirf...@gmail.com](https://code.google.com/u/111101869168605938405/) on May 23, 2013 15:25:15_

Hi,

I am having clustering environment with 2 memcache instances and 2 servers and added the jars in tomcat lib directory which are available in the site 
<a href="https://code.google.com/p/memcached-session-manager/wiki/SetupAndConfiguration" rel="nofollow">https://code.google.com/p/memcached-session-manager/wiki/SetupAndConfiguration</a>  &#13;
&#13;
While disabling the cookies am getting the data from the session.&#13;
&#13;
problem:&#13;
========&#13;
But with enabling cookies am not getting data from the session with multiple tabs on the same browser hitting at the same time.&#13;
&#13;
Expected:&#13;
========&#13;
It should work with enabling/Disabling cookies.&#13;
&#13;
Configuration in context.xml of tomcat:&#13;
&#13;
&lt;Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"&#13;
    memcachedNodes="n1:localhost:11211"&#13;
    sticky="false" &#13;
    operationTimeout="60000" &#13;
    sessionBackupTimeout="300000"&#13;
    sessionBackupAsync="false"&#13;
    lockingMode="none"&#13;
transcoderFactoryClass="de.javakaffee.web.msm.JavaSerializationTranscoderFactory"&#13;
    /&gt;&#13;
&#13;
Previous without clustering able to get the data in multiple tabs.&#13;
&#13;
When am searching with different search criterias in multiple tabs am able to get the data in one tab and am getting session as null for other tab in same browser.&#13;
&#13;
&#13;
Thanks.&#13;
&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=164_

**Comment by google-code-exporter** [comment] 2015-08-24 07:31
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 28, 2013 05:41:50_

<a title="Session data is coming as null for 2 servers and 2 memcache instances." class="closed_ref" href="/p/memcached-session-manager/issues/detail?id=165"> Issue 165 </a> has been merged into this issue.

**Comment by google-code-exporter** [comment] 2015-08-24 07:31
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 28, 2013 05:45:06_

Can you prepare a simple example application that allows me to reproduce the issue so that I can debug? Maybe you can use (a fork of) <a href="https://github.com/magro/msm-sample-webapp/tree/simpleservlet" rel="nofollow">https://github.com/magro/msm-sample-webapp/tree/simpleservlet</a> (the simpleservlet branch) as a starting point.

**Comment by google-code-exporter** [comment] 2015-08-24 07:31
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 14, 2013 03:14:32_

Any update on this? Can you show which http requests (with http headers) are sent from different tabs?

**Comment by google-code-exporter** [comment] 2015-08-24 07:31
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 15, 2013 03:54:11_

Update: I just cannot reproduce this and thus need more information.

**Comment by google-code-exporter** [comment] 2015-08-24 07:31
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 15, 2013 04:29:25_

Note2self: maybe related to <a title="multiple parallel requests for the same session with msm has problem" href="/p/memcached-session-manager/issues/detail?id=151">issue #151</a>

**Comment by magro** [comment] 2015-08-24 16:58
Former issue 151 is now issue #192

**Comment by magro** [comment] 2016-02-04 23:19
reopen if needed.

**Closed by magro** 2016-02-04 23:19 UTC
Labels: bug, imported, Priority-Medium
