### ISSUE TITLE
Deserialization fails on ConcurrentHashMap in Spring User object

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#187] opened 2015-08-24 00:21 UTC
_From [monster...@gmail.com](https://code.google.com/u/106829663774569401640/) on June 20, 2012 20:51:14_

<b>What steps will reproduce the problem?</b>
1. Try to serialize a spring User object that contains a TreeSet&#13;
<b>2.</b>
<b>3.</b>
&#13;
<b>What is the expected output? What do you see instead?</b>
&#13;
Correct serialization. Stack Trace&#13;
WARNING: Could not load session with id C85C5CD2388F9929DC99908ED6013146-n1 from memcached.&#13;
com.esotericsoftware.kryo.SerializationException: Unable to deserialize object of type: java.util.concurrent.ConcurrentHashMap&#13;
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:593)&#13;
	at com.esotericsoftware.kryo.ObjectBuffer.readObject(ObjectBuffer.java:213)&#13;
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.deserializeAttributes(KryoTranscoder.java:256)&#13;
	at de.javakaffee.web.msm.TranscoderService.deserializeAttributes(TranscoderService.java:159)&#13;
	at de.javakaffee.web.msm.TranscoderService.deserialize(TranscoderService.java:116)&#13;
	at de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1027)&#13;
	at de.javakaffee.web.msm.MemcachedSessionService.findSession(MemcachedSessionService.java:578)&#13;
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:196)&#13;
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2841)&#13;
	at org.apache.catalina.connector.Request.getSession(Request.java:2307)&#13;
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)&#13;
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:229)&#13;
	at org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper.createNewSessionIfAllowed(HttpSessionSecurityContextRepository.java:339)&#13;
	at org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper.saveContext(HttpSessionSecurityContextRepository.java:280)&#13;
	at org.springframework.security.web.context.HttpSessionSecurityContextRepository.saveContext(HttpSessionSecurityContextRepository.java:104)&#13;
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:87)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at com.redbox.digital.proxy.security.WSFedRememberMeAuthenticationFilter.doFilter(WSFedRememberMeAuthenticationFilter.java:104)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:201)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at com.redbox.digital.proxy.security.WSFedRequestParamPreAuthenticationFilter.doFilter(WSFedRequestParamPreAuthenticationFilter.java:195)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)&#13;
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)&#13;
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)&#13;
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)&#13;
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)&#13;
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)&#13;
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)&#13;
	at de.javakaffee.web.msm.SessionTrackerValve.invoke(SessionTrackerValve.java:126)&#13;
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:581)&#13;
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)&#13;
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)&#13;
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)&#13;
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)&#13;
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)&#13;
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)&#13;
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)&#13;
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:309)&#13;
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)&#13;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)&#13;
	at java.lang.Thread.run(Thread.java:722)&#13;
Caused by: com.esotericsoftware.kryo.SerializationException: Unable to deserialize object of type: org.springframework.security.core.context.SecurityContextImpl&#13;
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:571)&#13;
	at com.esotericsoftware.kryo.serialize.MapSerializer.readObjectData(MapSerializer.java:129)&#13;
	at com.esotericsoftware.kryo.Serializer.readObject(Serializer.java:61)&#13;
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:589)&#13;
	... 52 more&#13;
Caused by: com.esotericsoftware.kryo.SerializationException: Serialization trace:&#13;
authorities (org.springframework.security.core.userdetails.User)&#13;
principal (org.springframework.security.authentication.UsernamePasswordAuthenticationToken)&#13;
authentication (org.springframework.security.core.context.SecurityContextImpl)&#13;
	at com.esotericsoftware....

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=145_

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 20, 2012 18:25:49_

AFAICS the issue is that the spring User class uses a TreeSet initialized with a comparator (in User.sortAuthorities) and that kryo's CollectionSerializer creates just a new TreeSet (without comparator). This issue with the TreeSet might be interesting for the kryo project, although it probably won't be fixed for kryo1 as kryo2 is just hot and fresh (do you want to push it there?).

A solution for would be to write a custom serializer for the spring User object an register it as customConverter (msm config). You can check existing custom converters + kryo-serializers to see how to do this, e.g.:

<a href="https://github.com/magro/memcached-session-manager/blob/master/kryo-serializer/src/main/java/de/javakaffee/web/msm/serializer/kryo/JodaDateTimeRegistration.java" rel="nofollow">https://github.com/magro/memcached-session-manager/blob/master/kryo-serializer/src/main/java/de/javakaffee/web/msm/serializer/kryo/JodaDateTimeRegistration.java</a>&#13;
&#13;
and&#13;
&#13;
<a href="https://github.com/magro/kryo-serializers/blob/master/src/main/java/de/javakaffee/kryoserializers/jodatime/JodaDateTimeSerializer.java" rel="nofollow">https://github.com/magro/kryo-serializers/blob/master/src/main/java/de/javakaffee/kryoserializers/jodatime/JodaDateTimeSerializer.java</a>&#13;
&#13;
If you need any help you may ask on the mailing list.&#13;
&#13;
This serializer might also be a nice contribution to kryo-serializers / msm :-)

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [monster...@gmail.com](https://code.google.com/u/106829663774569401640/) on June 26, 2012 19:40:06_

Ill see if I can get to it :)

Worked around it for now with a new spring user object.

Kevin Clark (monster910)

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [netane...@gmail.com](https://code.google.com/u/108845001729273799484/) on August 28, 2013 06:33:28_

Hi Kevin/Martin,

How have you done the workaround?
If I will use other serializer will it work?

Thanks,
Netanel

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 28, 2013 08:37:05_

Hi Netanel,

the custom serializer for the spring User class has not yet found its way into kryo-serializers, so you could contribute it :-)

Do you still have questions regarding the custom serializer?

I'm not sure if the problem also exists with the default (java) serializer, you could try it (just remove the transcoderFactoryClass attribute).

Cheers,
Martin

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 28, 2013 13:00:37_

I hacked a customConverter for the Spring Security User class: <a href="https://gist.github.com/magro/6370466" rel="nofollow">https://gist.github.com/magro/6370466</a>&#13;
&#13;
This can be added to the msm config like this:&#13;
&#13;
...&#13;
customConverter="de.javakaffee.web.msm.serializer.kryo.SpringSecurityUserRegistration"&#13;
transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"&#13;
...&#13;
&#13;
Use it on your own risk, I haven't tested it! Feedback welcome.

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [steffen...@googlemail.com](https://code.google.com/u/109403461685878006584/) on August 29, 2013 05:54:49_

Hello Martin,

Thank you for writing this class. We currently are having exactly the same problem with ConcurrentHashMap and Tomcat MSM. We tried using your class, but still are getting the same Error. We have created a jar file of this SpringSecurityUserRegistration class, added it to Tomcat and registered the class in the manager as shown in your post. But unfortunately, nothing has changed. Is there anything else that needs attention for? We also already tried to register just the ConcurrentHashMap with the following class:

package tv.mashero.customkryo;
import java.util.concurrent.ConcurrentHashMap;
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.serialize.MapSerializer;
import de.javakaffee.web.msm.serializer.kryo.KryoCustomization;

public class CustomKryoRegistration implements KryoCustomization {
	
	public void customize(Kryo kryo) {
		kryo.register( ConcurrentHashMap.class, new MapSerializer(kryo) );  
	}
	
}

This example does not work, because a NoSuchMethodError for Kryo.register gets thrown:

SEVERE: Could not execute customization customkryo.CustomKryoRegistration@1d91eb90
java.lang.NoSuchMethodError: com.esotericsoftware.kryo.Kryo.register(Ljava/lang/Class;Lcom/esotericsoftware/kryo/Serializer;)Lcom/esotericsoftware/kryo/Registration;
	at tv.mashero.customkryo.CustomKryoRegistration.customize(CustomKryoRegistration.java:14)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.createKryo(KryoTranscoder.java:214)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.<init>(KryoTranscoder.java:117)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory.getTranscoder(KryoTranscoderFactory.java:61)
	at de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory.createTranscoder(KryoTranscoderFactory.java:47)
	at de.javakaffee.web.msm.MemcachedSessionService.createTranscoderService(MemcachedSessionService.java:474)
	at de.javakaffee.web.msm.MemcachedSessionService.startInternal(MemcachedSessionService.java:450)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.startInternal(MemcachedBackupSessionManager.java:128)
	at de.javakaffee.web.msm.MemcachedBackupSessionManager.start(MemcachedBackupSessionManager.java:637)

Has this to do with the old version of Kryo that MSM is using (currently only version 1)? Why MSM is still using the old Kryo 1 version and does not update Kryo to version 2? Do you have any ideas how to solve the problem?

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 29, 2013 09:16:56_

Have you built your CustomKryoRegistration with kryo1? If you have msm-kryo-serializer in your project/webapp you should have the correct kryo version (as transitive dependency if you're using maven) in place already. You can keep the CustomKryoRegistration besides your regular app classes - it must be loaded by the webapp classloader as it's the case for msm-kryo-serializer + kryo.

So msm-kryo-serializer + kryo etc. must be in WEB-INF/lib, your CustomKryoRegistration.class should be in WEB-INF/classes.

Is this the case?

Regarding kryo1 vs. kryo2: the kryo-serializers providing additional serializers is already ported to kryo2, but the tests for CGLibSerializer (or JdkProxySerializer, not sure) failed and I couldn't figure out what's the reason for this. This should be fixed, and then msm-kryo-serializer can be ported to kryo2.

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [monster...@gmail.com](https://code.google.com/u/106829663774569401640/) on August 29, 2013 11:04:05_

It has been awhile but I create a new user object and rewrote the methods failing.

/**
 * XXXX user details implementation. Pseudo model of the IIA Party-ContactPoint model.
 * 
 * @-author Kevin Clark
 *
 */

@-JsonIgnoreProperties({"authorities", "username", "password", "accountNonExpired", "accountNonLocked", "credentialsNonExpired", "enabled"})
public class ZoeUser implements UserDetails, CredentialsContainer {

I rewrote the sortAuthorities method to not use TreeSet

    private static Set<GrantedAuthority> sortAuthorities(Collection<? extends GrantedAuthority> authorities) {
        Assert.notNull(authorities, "Cannot pass a null GrantedAuthority collection");
        // Ensure array iteration order is predictable (as per UserDetails.getAuthorities() contract and SEC-717)
        List<GrantedAuthority> sortedAuthorities =  new ArrayList<GrantedAuthority>(authorities);
 
        for (GrantedAuthority grantedAuthority : authorities) {
            Assert.notNull(grantedAuthority, "GrantedAuthority list cannot contain any null elements");
            sortedAuthorities.add(grantedAuthority);
        }
        Collections.sort(sortedAuthorities, new AuthorityComparator());

        return new HashSet<GrantedAuthority>(sortedAuthorities);
    }

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [steffen...@googlemail.com](https://code.google.com/u/109403461685878006584/) on August 30, 2013 05:53:47_

Hello Martin,

The classes are not laying inside the WEB-INF/classes folder, because Tomcat needs to use it in a global context. On our Tomcat several Applications are running, not only the one using Spring Security. Thats why we created a jar file for the class and added it to Tomcat, not to the Application. If we use the class in the Application itself and register it in Tomcats context.xml, then there is the problem Tomcat can not start anymore, because then Tomcat can not find the class.

The NoSuchMethodError for the CustomKryoRegistration class occured propably because we were using a Kryo 2 Version, so it wasnt compatible. We tried it again now using Kryo 1, created a jar file of this CustomKryoRegistration class, added it to Tomcat and registered the class within the customConverter attribute in the Tomcats context.xml. This is our context.xml we do use:

<Context>
    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
      memcachedNodes="devapp0:10.10.1.14:11211 devapp1:10.10.1.34:11211"
      sticky="false"
      lockingMode="auto"
      requestUriIgnorePattern=".*\.(png|gif|jpg|css|js)$"
      customConverter="customkryo.CustomKryoRegistration"
      transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
    />
</Context>

The class CustomKryoRegistration is, how i sayd, packed into a jar file named CustomKryo.jar that is added to the Tomcat. The NoSuchMethodError is gone, but the main problem continues, the Error "Unable to deserialize object of type: java.util.concurrent.ConcurrentHashMap" still occures. Somehow it looks like the class maybe just dont get used. Is there anything we are doing wrong or something else we have to pay attention for?

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 30, 2013 16:01:52_

@-monster910: as you're using a HashMap you can even remove all the sorting stuff. Alternatively use a LinkedHashMap to retain sort order.

**Comment by google-code-exporter** [comment] 2015-08-24 00:21
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 30, 2013 16:11:38_

@-steffen.sz I just noticed that your CustomKryoRegistration covers ConcurrentHashMap, that doesn't change anything. The ConcurrentHashMap is not the problem.
You need to configure the serializer/registration I provided. If it does not work please post the actually used configuration, logs from tomcat start with debug logging enabled and the full stacktrace.

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [steffen...@googlemail.com](https://code.google.com/u/109403461685878006584/) on September 02, 2013 06:00:02_

Hello Martin,

Thank you very much for your help. We used the serializer class SpringSecurityUserRegistration you provided. Only i had to remove the @-Override on the customize function since this created an compile Error in Java:
 - The method customize(Kryo) of type SpringSecurityUserRegistration must override a superclass method
 - implements de.javakaffee.web.msm.serializer.kryo.KryoCustomization.customize
I guess it wasnt really your intention to override the customize function there?

The class SpringSecurityUserRegistration is packaged to a jar file named "KryoUserSerializer.jar", and is added to the Tomcat together with all other jar files. But without any success. Since the logs and stacktrace etc. are very large, i made a Text file and added it as attachement to this post. It should contain all information. Thanks again very much for your help.

**Attachment:** [LogsAndConfiguration.txt](http://code.google.com/p/memcached-session-manager/issues/detail?id=145#hc12)

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 03, 2013 01:57:05_

Re @Override annotation: sounds as if you're building with java5, with java6 the @-Override is valid for overridden methods from an interface.

From the attached logs it seems as if the SpringSecurityUserRegistration is not used to deserialized the user object. Did you start with a clean memcached, so that it's sure that msm does not try to deserialize a session serialized without the registered SpringSecurityUserRegistration?
If that was the case can you provide a very simple sample app that allows me to reproduce/debug this issue?

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [steffen...@googlemail.com](https://code.google.com/u/109403461685878006584/) on September 04, 2013 00:43:58_

Hi Martin,

We also cleaned the memcached, but its the same result. I will try to get an example app during the next days.

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 04, 2013 00:50:12_

Ok

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [steffen...@googlemail.com](https://code.google.com/u/109403461685878006584/) on October 08, 2013 02:15:55_

Hello Martin,

Sorry it toke a while, but finaly we worked out a good solution. We figured out byself where the error was coming from. When using the SpringSecurityUserRegistration class you provided, it introduces direct and indicect dependencies to the spring-security packages and others, which must be included within the tomcat server lib. The error still occured because some neccessary packages were missing there. However, moving all the jar from the war archive to the server-library seems to be an ugly side effect, because it breaks the servlet-container/application architecure to separate server and application code /libraries.

Since this could be problematic for us and may cause other problems, we gave up on using the SpringSecurityUserRegistration class and just fixed the bug in the kryo1 version itself, which is been the main source of the problem at all. We updated the kryo1 package, creating a new version 1.04.1 of kryo. With this, the serializing bug is fixed now, the error is not occuring anymore.

We added the fixed kryo1 version as attachment, so if possible, you can make a test with it, checking whether it is working still correct when using it together with MSM. The attachment includes the final kryo-1.04.1.jar and its sources as complete project that can be build with maven. 

Also it would be nice to put the patch into the kryo repository, to help others who are having the same issue. What you think about it?

**Attachment:** [kryotest-package.zip](http://code.google.com/p/memcached-session-manager/issues/detail?id=145#hc16)

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 09, 2013 00:31:41_

Great analysis! Can you submit an issue with a patch in the kryo issue tracker?
Regarding the fix: In Kryo.newSerializer I'd use
  TreeMap.class.isAssignableFrom(type)
instead of
  type.getName().equals(TreeMap.class.getName()).

Is there a reason why you chose the latter way?

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 11, 2013 05:36:15_

Btw, I've added TreeMap/SetSerializer for kryo1 (and TreeSetSerializer to kryo2, because kryo2 already had a TreeMapSerializer), and will cut a new kryo1 release soon. I'll drop a not here once this is available.

Here's the change in kryo 1: <a href="https://code.google.com/p/kryo/source/detail?r=419" rel="nofollow">https://code.google.com/p/kryo/source/detail?r=419</a>

**Status:** Started

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [steffen...@googlemail.com](https://code.google.com/u/109403461685878006584/) on October 14, 2013 03:13:09_

Hello Martin,

Thank you for adding the update to kryo. Regarding to the fix: using type.getName().equals(TreeMap.class.getName() avoids serializing subclasses for which specific serializers might be requird. 

When using the method isAssignableFrom(mytype) for a derived TreeMap class with additional fields, serializing the additional fields would not happen, and no error would be produced. The resulting error would be quite similar to the 1.04 implementation, which made a cast of the TreeMap to a collection and missed to serialize the comparator field.

Do you think this could be a problem?

**Comment by google-code-exporter** [comment] 2015-08-24 00:22
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 20, 2013 14:55:42_

<i>(No comment was entered for this change.)</i>

**Blockedon:** memcached-session-manager:189

**Comment by magro** [comment] 2015-08-24 15:44
Closed for now due to inactivity. Please reopen if still relevant.

**Closed by magro** 2015-08-24 15:44 UTC
Labels: bug, imported, Priority-Medium

**Comment by pawanpec** [comment] 2015-09-25 06:44
i have used de.javakaffee.web.msm.JavaSerializationTranscoderFactory class instead of de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory.

Its working fine.
