### ISSUE TITLE
Can't make non-sticky sessions to work

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#265] opened 2015-08-24 08:04 UTC
_From [madskaddie@gmail.com](https://code.google.com/u/madskaddie@gmail.com/) on March 25, 2015 15:03:41_

Greetings,

I need to share sessions between several tomcat (v6) instances in non sticky session mode.  My problem is that the session is not either saved or restored correctly.

I've started with version 1.8.3 but tried 1.8.0 and 1.7.0 on tomcat6 (correct memcached jars added) on a linux box

I have attached a simple Servlet that only increments an integer and saves it to the session. With the standard session manager or with memcached based manager in sticky mode works as expected. When I switch to sticky=false, the counter value is maintained across successive requests

What am I missing ?

Thanks for your help

**Attachment:** [SimpleServlet.java web.xml context.xml](http://code.google.com/p/memcached-session-manager/issues/detail?id=226)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=226_

**Comment by google-code-exporter** [comment] 2015-08-24 08:04
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 25, 2015 12:18:13_

Are you sure that the counter is incremented? What does the System.err.println("foobar: "+counter.toString()); print? I can imagine that the counter++ does not really increment it because the Integer is unboxed first...

**Comment by google-code-exporter** [comment] 2015-08-24 08:04
_From [madskaddie@gmail.com](https://code.google.com/u/madskaddie@gmail.com/) on March 26, 2015 03:59:56_

Yes, I'm sure  because it works with both the standard tomcat session manager and with memcached in sticky mode (but I can't find a decent documentation that explicitly states that box/unboxed integers work the same way). I'm uploading a cleaner version (the behaviour is a bit different) and a compiled war.

This is a simpler example that I built just to simplify things. I pretend to use this in a Wicket application. Since it wasn't working, I decided to take Wicket out of the way and moved to the simplest cenario: a servlet.

**Attachment:** [session-test-0.0.1-SNAPSHOT.war SimpleServlet.java](http://code.google.com/p/memcached-session-manager/issues/detail?id=226#hc2)

**Comment by piyush-mukati** [comment] 2016-01-27 02:29
I also faced similar issue my application  works with both the standard tomcat session manager and with memcached in sticky mode. but i noticed some session data loss with memcached in non sticky mode.

**Comment by magro** [comment] 2016-02-02 17:28
@piyush-mukati I just added the test servlet to the samples.

Running 2 memcacheds and then in the samples dir

    $ mvn tomcat7:run -pl :simpleservlet -am -Djava.util.logging.config.file=src/main/resources/logging.properties

allows to request http://localhost:9090/counter - but for me it counts
correctly, so I cannot reproduce the issue.

Can you reproduce the issue and provide a reproducable sample?

**Comment by magro** [comment] 2016-03-07 22:54
Any feedback, @piyush-mukati ?

**Comment by LorenzoBoccaccia** [comment] 2016-07-13 20:32
ok, I can get some feedback here as I'm trying the same thing

setup is: haproxy with 3 tomcats as backend, sticky session managed by haproxy (to avoid issues with jsessionid jvmpath)

non sticky setup of tomcat-memcached as follow (the idea is to keep session locality using the haproxy stickyness but allow failover using non-sticky configuration)

context.xml is straightforward:

```
    <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager" 
    memcachedNodes="memcached-001:11211"
    sticky="false"
    transcoderFactoryClass="de.javakaffee.web.msm.JavaSerializationTranscoderFactory"
    />   

```

the session gets set correctly on the client and sent as well, but gets ignored:
```
==> /var/log/tomcat7/catalina.2016-07-13.log <==
Jul 13, 2016 4:26:45 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugRequestSessionCookie
FINE: Have request session cookie: domain=null, maxAge=-1, path=null, value=230D242DBA132DBA975F5767CCACB7A6, version=0, secure=false

==> /var/log/tomcat7/catalina.out <==
Jul 13, 2016 4:26:45 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugRequestSessionCookie
FINE: Have request session cookie: domain=null, maxAge=-1, path=null, value=230D242DBA132DBA975F5767CCACB7A6, version=0, secure=false

==> /var/log/tomcat7/catalina.2016-07-13.log <==
Jul 13, 2016 4:26:45 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugResponseCookie
FINE: Request finished, with Set-Cookie header: JSESSIONID=79E19B084ADA93534563CA154EE151E9; Path=/; Secure; HttpOnly

==> /var/log/tomcat7/catalina.out <==
Jul 13, 2016 4:26:45 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugResponseCookie
FINE: Request finished, with Set-Cookie header: JSESSIONID=79E19B084ADA93534563CA154EE151E9; Path=/; Secure; HttpOnly

```

as you can see the cookies arrives correct but gets sent back modified; 

this is the same call client side, you can check the cookies being sent received
![image](https://cloud.githubusercontent.com/assets/3062853/16818726/866ac79a-4949-11e6-8023-501bd94a7582.png)


memcached storage works fine:

```
stats items
STAT items:3:number 1
STAT items:3:age 6
STAT items:3:evicted 0
STAT items:3:evicted_nonzero 0
STAT items:3:evicted_time 0
STAT items:3:outofmemory 0
STAT items:3:tailrepairs 0
STAT items:3:reclaimed 0
STAT items:3:expired_unfetched 0
STAT items:3:evicted_unfetched 0
END
stats cachedump 3 100
ITEM validity:230D242DBA132DBA975F5767CCACB7A6 [20 b; 1468443339 s]
END

```

and I'm using the root context path for my webapp

**Comment by magro** [comment] 2016-07-13 21:41
1. What are you trying to achieve with haproxy stickyness + non-sticky msm configuration? msm supports failover for sticky configuration as well (it was originally built for this) 
2. Can you try to reproduce your issue with the msm samples (see my comment above)? Please try sticky/sticky as well.

**Comment by LorenzoBoccaccia** [comment] 2016-07-14 06:56
1) to have one central memcached node for all tomcats to store and retrieve sessions; as far as I understand the documetation for the sticky failover to work I'd need to have a local memcached at every node and define as failover every other node memcached; I'm trying to avoid that because it will grow geometrically with the number of nodes and I'm not on the fastest cloud provider to begin with and I'm trying to move the session away from the "replicated on every node" model to avoid using excessive memory.

2) will try

**Comment by magro** [comment] 2016-07-14 22:18
You can also use msm with sticky=true and a single memcached. You'll achieve better performance with this and high availability as well.

**Comment by LorenzoBoccaccia** [comment] 2016-07-15 12:52
ok that one worked! thanks!

**Comment by magro** [comment] 2016-07-16 20:29
Great to hear that! 

Closing this issue for now.

**Closed by magro** 2016-07-16 20:29 UTC
Labels: bug, imported, needs-feedback, Priority-Medium
