### ISSUE TITLE
Root context session conflicts with existing sessions

### ISSUE THREAD

**Issue by lavanyakc** [magro/memcached-session-manager#272] opened 2015-09-23 02:38 UTC
Hi,
I have a problem with `MemcachedSessionService#findSession` code (memcached 1.8.3 + tomcat 7.0.26 + non sticky session + locking mode auto) and the below configuration

    <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
    	memcachedNodes="n1:localhost:5701" sticky="false" sessionBackupAsync="false"
     	sessionBackupTimeout="30000" operationTimeout="60000" lockingMode="auto"
    	requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)" />

I have a jsp in ROOT war which creates a session and whenever I access this, it causes findSession to return null for the existing sessions in different contexts. I tried commenting the below code in findSession to ensure session always loads from memcahed.

            if ( !_sticky && isContainerSessionLookup()
                    && !_manager.contextHasFormBasedSecurityConstraint() ) {
                // we can return just null as the requestedSessionId will still be set on
                // the request.
                return null;
            }
            // If no current request is set (RequestTrackerHostValve was not passed) we got invoked
            // by CoyoteAdapter.parseSessionCookiesId - here we can just return null, the requestedSessionId
            // will be accepted anyway
            if(!_sticky && _currentRequest.get() == null) {
                return null;
            }

but that results in an exception in `LockingStrategyAuto#onBeforeLoadFromMemcached` as currentRequest.get returns null.
`WARNING: Could not load session with id 0F7551F6E35C540E0532C863F37FA5C1-n1 from    memcached.java.lang.RuntimeException: There's no request set, this indicates that this findSessionwas triggered by the container which should already be handled in findSession.`

I think there is an issue with findSession code when there is a JSESSIONID cookie with root context. 

Thanks for any help,
Lavanya.

**Comment by magro** [comment] 2015-09-23 06:49
Hi Lavanya,

Am 23.09.2015 04:38 schrieb "lavanyakc" <notifications@github.com>:
>
> I think there is an issue with findSession code when there is a
JSESSIONID cookie with root context.

Because it works well for many other people I'd assume that there's
something special/different with your application. Can you provide a simple
reproducable sample? You might try to reproduce this based on the samples
https://github.com/magro/memcached-session-manager/tree/master/samples

Cheers,
Martin

**Comment by lavanyakc** [comment] 2015-09-25 18:32
Hi Martin,
I created a reproducible sample with a similar configuration as our application. It is reproducible with a single server also. 
The sample can be downloaded at [memcahced-sample](http://wikisend.com/download/207180/memcached-root-sample.zip) with all the required config, debug enabled. It is a simple app, with one jsp which writes to the session and the other reads from session. And the index.jsp in the ROOT redirects to read.jsp. Once you run the tomcat server, accessing http://localhost:8080/root-session-sample/write.jsp will write data in the session. http://localhost:8080/root-session-sample/read.jsp will read data, you can see that the value will be read properly but if one hits http://localhost:8080/ (root context), the next read will lose the session-data. The same will work fine if we remove memcached session manager configuration in tomcat context.xml. 

Let me know if you need any other details.

Thanks in advance,
Lavanya.

**Comment by lavanyakc** [comment] 2015-10-01 05:18
Hi Martin,
Did you get a chance to look into the sample?
Thanks,
Lavanya.

**Comment by magro** [comment] 2015-10-02 23:11
Hi Lavanya, sorry that I didn't find time yet, hopefully on monday. Cheers,
Martin
Am 01.10.2015 07:18 schrieb "lavanyakc" <notifications@github.com>:

**Comment by magro** [comment] 2015-10-05 04:09
@lavanyakc At the url you shared (http://wikisend.com/download/207180/memcached-root-sample.zip) I'm only seeing a link to http://wikisend.com/download/207180/RegalBliss.rar - which only contains some images. Where is your sample (direct link)? You might just use github to prepare the sample... (Really sad that now I cannot work on this, I have 4 hours on a train, the next days are going to be very busy again...)

**Comment by lavanyakc** [comment] 2015-10-05 04:45
Hi Martin,

Can you try this link now http://wikisend.com/download/836392/memcached-root-sample.zip . Look into this if you get time. I was busy with other things so could not create a git sample, I will try to create a git sample later this week.

Thanks
Lavanya.

**Comment by magro** [comment] 2015-10-05 06:00
`wget http://wikisend.com/download/836392/memcached-root-sample.zip`
just gives me an html document. Please provide a direct link that does
not need any login or I don't know.

If possible please don't include tomcat itself in the archive, because
my internet connection currently is really really crappy.

**Comment by lavanyakc** [comment] 2015-10-05 06:11
Hi Martin,
This sample was created with hazelcast server and the tomcat has all the required libs for that and listener to start hazelcast. I thought it would be easier to run, so sent it with server. I will create a sample for memcached server and post again which may take some time for me.
Thanks,
Lavanya.

**Comment by magro** [comment] 2015-10-05 06:23
Ok. Is hazelcast involved in this issue, or is the issue unrelated to
hazelcast? Please provide a sample that includes only things, that are
needed to reproduce the issue. Everything that can be removed and the
issue is still there should be removed.

You can also build upon the samples here:
https://github.com/magro/memcached-session-manager/tree/master/samples -
this allows to have a mavenized/reproducable app running in tomcat.

**Comment by lavanyakc** [comment] 2015-10-05 06:26
It can be reproducible with memcached server. I will create a mavenized memcached only sample and will send you. 

Thanks,
Lavanya.

**Comment by magro** [comment] 2016-02-04 23:42
Seems to be a duplicate of #197

**Comment by magro** [comment] 2016-02-05 07:59
@lavanyakc As long as there's no better solution in msm a possible workaround would be to use [different session cookie names for different contexts](http://stackoverflow.com/questions/877064/changing-cookie-jsessionid-name).

**Comment by magro** [comment] 2016-02-05 08:22
For further discussion let's use #197.

**Closed by magro** 2016-02-05 08:22 UTC

**Comment by lavanyakc** [comment] 2016-02-05 08:43
Hi Martin,

We have already worked around this problem by using different cookie names for root context. So I am not looking for a fix for this right now.

Thanks,
Lavanya.

**Comment by magro** [comment] 2016-02-05 10:09
Ok, great!
