### ISSUE TITLE
Tomcat is creating a new session id on every request.

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#252] opened 2015-08-24 07:39 UTC
_From [r.pr...@gmail.com](https://code.google.com/u/112943744453570208114/) on August 13, 2014 18:42:36_

Hello,

 Tomcat is creating a new session id on every request.

Example:

When I access the url http://localhost/backend three times 3 ids were generated in each of the requests and I can never login because of the captcha code.

What am i doing wrong?

Versions:
apache-tomcat-7.0.50
memcached-session-manager-1.8.2.jar
memcached-session-manager-tc7-1.8.2.jar
spymemcached-2.11.1.jar

<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
         memcachedNodes="n1:localhost:11211"
         sticky="false"
         lockingMode="none"
	 sessionBackupAsync="false"
         sessionBackupTimeout="1000"
	 requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"/>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=211_

**Comment by google-code-exporter** [comment] 2015-08-24 07:39
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 13, 2014 10:28:15_

Please configure debug logging according to the docs and provide the related log output.

**Comment by google-code-exporter** [comment] 2015-08-24 07:39
_From [r.pr...@gmail.com](https://code.google.com/u/112943744453570208114/) on August 13, 2014 11:03:28_

<i>(No comment was entered for this change.)</i>

**Attachment:** [catalina.log](http://code.google.com/p/memcached-session-manager/issues/detail?id=211#hc2)

**Comment by google-code-exporter** [comment] 2015-08-24 07:39
_From [r.pr...@gmail.com](https://code.google.com/u/112943744453570208114/) on August 15, 2014 07:03:32_

Hi Martin,

  I found another problem that may be related to the above. I'll try to explain the scenario:
  
I have 1 tomcat using memcached with 2 applications (two .war)

First Application

backend.war
Context Path: "/backend"
Url: http://localhost:8080/backend

Second Application

ROOT.war
Context Path: "/"
Url: http://localhost:8080/

When I access the second url, tomcat/memcached generated a new session with id 471CC32D5AF17E703F43408A03EBEA56-n1 . Its works without any problem. When I try to access the url http://localhost:8080/backend/login the server receive 
the same session id 471CC32D5AF17E703F43408A03EBEA56-n1, then the admin application will generate a new session id on each request. The ids are conflicting between the two applications.

How can i use memcached with an application using context path "/"?

Thank You

**Comment by magro** [comment] 2016-02-04 23:32
Seems to be a duplicate of #197

**Comment by magro** [comment] 2016-02-05 07:58
As long as there's no better solution in msm a possible workaround would be to use [different session cookie names for different contexts](http://stackoverflow.com/questions/877064/changing-cookie-jsessionid-name).

**Closed by magro** 2016-02-05 07:58 UTC
Labels: bug, imported, Priority-Medium
